## Copy Repo files
- name: Import Clemlab Jenkins publishing key
  apt_key:
    url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x449E83E81403D1C5
    state: present


- name: Copy Repo
  copy:
    src: "{{ item }}"
    dest: /etc/apt/sources.list.d/
  when: offline_apt_repos is defined and offline_apt_repos
  with_fileglob:
    - "{{source_repo_folder}}/*.list"



- name: Required packages (apt)
  package: name={{item}} state=present use=apt
  with_items:
    - vim-common
    - tree
    - git
    - nano
    - vim
    - unzip
    - net-tools
    - wget

- name: update apt cache
  shell: 'apt update -y'
