- include: prepare_os.yml
  when: prepare_os is defined and prepare_os

- include: yum_repos.yml
  when: yum_repos

- include: prepare_fs.yml
  when: prepare_fs is defined and prepare_fs and fs is defined and {{ fs | count }} > 0
  with_items: "{{fs}}"

- include: users_hdp.yml
  when: create_users is defined and create_users

- include: upload_certs.yml
  when: security_ssl_cert_folder is defined

- include: freeipa_client.yml
  when: freeipa_client is defined and freeipa_client

- include: krb5_client.yml
  when: krb5_client is defined and krb5_client

- include: krb5_services.yml
  when: create_principals is defined and create_principals
  with_items: "{{krb5_services}}"

- include: oracle_jdk.yml
  when: oracle_jdk

- include: open_jdk.yml
  when: open_jdk

- include: cgroups.yml
  when: cgroups_enable is defined and cgroups_enable

- include: prometheus.yml
  when: prometheus is defined and prometheus

