
- block:
  - name: Install open 8 JDK (RHEL 7/8/9)
    package: name={{item}} state=installed
    with_items:
      - java-1.8.0-openjdk-devel
    when: system_major_distribution == "redhat"

  - name: Install open 8 JDK (Ubuntu 22)
    package: name={{item}} state=present use=apt
    with_items:
      - openjdk-8-jdk
    when: system_major_distribution == "ubuntu"
  when: open_jdk_version == 8

- block:
  - name: Install open 11 JDK (RHEL 8)
    package: name={{item}} state=installed
    with_items:
      - java-11-openjdk
      - java-11-openjdk-devel
    when: system_major_distribution == "redhat"

  - name: Install open 11 JDK (Ubuntu 22)
    package: name={{item}} state=present use=apt
    with_items:
      - openjdk-11-jdk
      - openjdk-11-jdk-devel
    when: system_major_distribution == "ubuntu"
  when: open_jdk_version == 11

- block:
  - name: Install open 17 JDK (RHEL 8)
    package: name={{item}} state=installed
    with_items:
      - java-17-openjdk
      - java-17-openjdk-devel
    when: system_major_distribution == "redhat"

  - name: Install open 17 JDK (Ubuntu 22)
    package: name={{item}} state=present use=apt
    with_items:
      - openjdk-17-jdk
      - openjdk-17-jdk-devel
    when: system_major_distribution == "ubuntu"
  when: install_openjdk_17