
- name: Install open JDK
  yum: name={{item}} state=installed
  with_items:
    - java-1.8.0-openjdk-devel
  when: provider is defined and provider == 'yum' and open_jdk_version == 8


- name: Install open JDK
  yum: name={{item}} state=installed
  with_items:
    - java-11-openjdk-devel
  when: provider is defined and provider == 'yum' and open_jdk_version == 11





