## Import new AlmaLinux RPM Key starting January 12th 2024
- name: Import AlmaLinux GPG key
  shell: 'rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux'
  when: ansible_distribution == "AlmaLinux"


## Delete Centos Repo
- name:  Delete Centos Files
  file:
   path: "{{ item }}"
   state: absent
  when: not sattelite_repo and offline_yum_repos
  with_items:
  - /etc/yum.repos.d/CentOS-Base.repo
  - /etc/yum.repos.d/CentOS-CR.repo

## Copy Repo files

- name: Copy Repo
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
  when: offline_yum_repos
  with_fileglob:
    - "{{source_repo_folder}}/*.repo"

## Required Packages
- debug:
    msg: "{{ansible_distribution}} {{ansible_distribution_major_version}}"

- name: fetch epel
  shell: "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm"
  when: system_major_distribution == "redhat" # and ansible_distribution != "RedHat"

- name: Clean DBCache
  command: yum clean all
